@extends('super-admin.layout')
@section('title', 'Admin Users')
@section('subtitle', 'Manage Super Admin, Sales Admin, Support Admin, and Finance Admin users.')
@section('content')
<div class="d-flex justify-content-end mb-3"><a class="btn btn-primary" href="{{ route('super-admin.admin-users.create') }}">Create admin user</a></div>
<div class="platform-card p-3 table-responsive"><table class="table align-middle"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last login</th><th>Actions</th></tr></thead><tbody>
@forelse($admins as $admin)<tr><td><strong>{{ $admin->name }}</strong><div class="small text-muted">{{ $admin->email }} {{ $admin->phone }}</div></td><td>{{ ucwords(str_replace('_',' ', $admin->role)) }}</td><td><span class="status-badge status-{{ $admin->is_active ? 'active' : 'disabled' }}">{{ $admin->is_active ? 'Active' : 'Disabled' }}</span></td><td>{{ optional($admin->last_login_at)->format('M j, Y g:ia') ?? 'Never' }}</td><td class="actions-row"><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.admin-users.edit', $admin) }}">Edit</a><form method="POST" action="{{ route('super-admin.admin-users.toggle', $admin) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-dark">{{ $admin->is_active ? 'Disable' : 'Enable' }}</button></form><form method="POST" action="{{ route('super-admin.admin-users.reset-password', $admin) }}" onsubmit="return confirm('Reset this admin password?')">@csrf<button class="btn btn-sm btn-outline-secondary">Reset password</button></form><form method="POST" action="{{ route('super-admin.admin-users.destroy', $admin) }}" onsubmit="return confirm('Deactivate this admin user safely?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Deactivate</button></form></td></tr>@empty<tr><td colspan="5" class="text-muted">No internal admin users found.</td></tr>@endforelse
</tbody></table>{{ $admins->links() }}</div>
@endsection
