<div class="platform-card p-3">
    <div class="row g-3">
        <div class="col-md-6"><label class="form-label">Payment record</label><select class="form-select" name="payment_record_id"><option value="">Not linked</option>@foreach($payments as $payment)<option value="{{ $payment->id }}" @selected(old('payment_record_id', $paymentDispute->payment_record_id)==$payment->id)>{{ $payment->payment_reference ?: 'Payment #'.$payment->id }} - {{ $payment->school?->name ?? 'No school' }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label">School</label><select class="form-select" name="school_id"><option value="">No school</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected(old('school_id', $paymentDispute->school_id)==$school->id)>{{ $school->name }}</option>@endforeach</select></div>
        <div class="col-md-8"><label class="form-label">Subject</label><input class="form-control" name="subject" value="{{ old('subject', $paymentDispute->subject) }}" required></div>
        <div class="col-md-4"><label class="form-label">Disputed amount</label><input class="form-control" type="number" min="0" step="0.01" name="disputed_amount" value="{{ old('disputed_amount', $paymentDispute->disputed_amount) }}"></div>
        <div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['open','investigating','resolved','rejected','closed'] as $status)<option value="{{ $status }}" @selected(old('status', $paymentDispute->status ?: 'open')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label">Priority</label><select class="form-select" name="priority">@foreach(['low','medium','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(old('priority', $paymentDispute->priority ?: 'medium')===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label">Assign finance admin</label><select class="form-select" name="assigned_admin_id"><option value="">Unassigned</option>@foreach($admins as $admin)<option value="{{ $admin->id }}" @selected(old('assigned_admin_id', $paymentDispute->assigned_admin_id)==$admin->id)>{{ $admin->name }}</option>@endforeach</select></div>
        <div class="col-12"><label class="form-label">Dispute description</label><textarea class="form-control" rows="5" name="description" required>{{ old('description', $paymentDispute->description) }}</textarea></div>
        <div class="col-12"><label class="form-label">Finance notes</label><textarea class="form-control" rows="4" name="finance_notes">{{ old('finance_notes', $paymentDispute->finance_notes) }}</textarea></div>
    </div>
</div>
<div class="mt-3 d-flex gap-2"><button class="btn btn-primary">{{ $button }}</button><a class="btn btn-outline-secondary" href="{{ route('super-admin.payment-disputes.index') }}">Cancel</a></div>
