<div class="platform-card p-3"><div class="row g-3">
<div class="col-md-4"><label class="form-label">School</label><select class="form-select" name="school_id"><option value="">No school</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected(old('school_id', $supportTicket->school_id)==$school->id)>{{ $school->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Owner</label><select class="form-select" name="school_owner_id"><option value="">No owner</option>@foreach($schools as $school)@if($school->owner)<option value="{{ $school->owner->id }}" @selected(old('school_owner_id', $supportTicket->school_owner_id)==$school->owner->id)>{{ $school->owner->name }} - {{ $school->name }}</option>@endif @endforeach</select></div>
<div class="col-md-4"><label class="form-label">Assigned support admin</label><select class="form-select" name="assigned_admin_id"><option value="">Unassigned</option>@foreach($admins as $admin)<option value="{{ $admin->id }}" @selected(old('assigned_admin_id', $supportTicket->assigned_admin_id)==$admin->id)>{{ $admin->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Subject</label><input class="form-control" name="subject" value="{{ old('subject', $supportTicket->subject) }}" required></div>
<div class="col-md-3"><label class="form-label">Priority</label><select class="form-select" name="priority">@foreach(['low','medium','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(old('priority', $supportTicket->priority ?: 'medium')===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['open','in_progress','resolved','closed'] as $status)<option value="{{ $status }}" @selected(old('status', $supportTicket->status ?: 'open')===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Message</label><textarea class="form-control" rows="6" name="message" required>{{ old('message', $supportTicket->message) }}</textarea></div>
<div class="col-md-6"><label class="form-label">Internal notes</label><textarea class="form-control" rows="6" name="internal_notes">{{ old('internal_notes', $supportTicket->internal_notes) }}</textarea></div>
</div></div><div class="mt-3"><button class="btn btn-primary">{{ $button }}</button> <a class="btn btn-outline-secondary" href="{{ route('super-admin.support-tickets.index') }}">Cancel</a></div>
