@extends('super-admin.layout')
@section('title', 'Support Tickets')
@section('subtitle', 'Assign, prioritize, and close platform support tickets.')
@section('content')
<div class="platform-card p-3 mb-3"><form class="row g-2 align-items-end" method="GET"><div class="col-md-4"><label class="form-label">Search subject</label><input class="form-control" name="search" value="{{ request('search') }}"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option>@foreach(['open','in_progress','resolved','closed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Priority</label><select class="form-select" name="priority"><option value="">All</option>@foreach(['low','medium','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(request('priority')===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary">Filter</button> <a class="btn btn-primary" href="{{ route('super-admin.support-tickets.create') }}">Create</a></div></form></div>
<div class="platform-card p-3 table-responsive"><table class="table align-middle"><thead><tr><th>Ticket</th><th>School</th><th>Priority</th><th>Status</th><th>Assigned</th><th>Actions</th></tr></thead><tbody>
@forelse($tickets as $ticket)<tr><td><strong>{{ $ticket->subject }}</strong><div class="small text-muted">{{ $ticket->created_at->format('M j, Y') }}</div></td><td>{{ $ticket->school?->name ?? 'No school' }}<div class="small text-muted">{{ $ticket->owner?->name }}</div></td><td><span class="status-badge status-{{ $ticket->priority }}">{{ ucfirst($ticket->priority) }}</span></td><td><span class="status-badge status-{{ $ticket->status }}">{{ ucfirst(str_replace('_',' ',$ticket->status)) }}</span></td><td>{{ $ticket->assignedAdmin?->name ?? 'Unassigned' }}</td><td class="actions-row"><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.support-tickets.show', $ticket) }}">View</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('super-admin.support-tickets.edit', $ticket) }}">Edit</a></td></tr>@empty<tr><td colspan="6" class="text-muted">No support tickets found.</td></tr>@endforelse
</tbody></table>{{ $tickets->links() }}</div>
@endsection
