@extends('super-admin.layout')
@section('title', 'Demo Requests')
@section('subtitle', 'Manage school demo leads and sales follow-up.')
@section('content')
<div class="platform-card p-3 mb-3"><form class="row g-2 align-items-end" method="GET"><div class="col-md-6"><label class="form-label">Search</label><input class="form-control" name="search" value="{{ request('search') }}"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option>@foreach(['new','contacted','scheduled','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-outline-primary">Filter</button> <a class="btn btn-primary" href="{{ route('super-admin.demo-requests.create') }}">Create</a></div></form></div>
<div class="platform-card p-3 table-responsive"><table class="table align-middle"><thead><tr><th>School</th><th>Contact</th><th>Status</th><th>Assigned</th><th>Preferred date</th><th>Actions</th></tr></thead><tbody>
@forelse($demoRequests as $demoRequest)<tr><td><strong>{{ $demoRequest->school_name }}</strong><div class="small text-muted">{{ $demoRequest->location }}</div></td><td>{{ $demoRequest->contact_person }}<div class="small text-muted">{{ $demoRequest->email }} {{ $demoRequest->phone }}</div></td><td><span class="status-badge status-{{ $demoRequest->status }}">{{ ucfirst($demoRequest->status) }}</span></td><td>{{ $demoRequest->assignedAdmin?->name ?? 'Unassigned' }}</td><td>{{ optional($demoRequest->preferred_demo_date)->format('M j, Y g:ia') ?? 'Not set' }}</td><td class="actions-row"><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.demo-requests.show', $demoRequest) }}">View</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('super-admin.demo-requests.edit', $demoRequest) }}">Edit</a><form method="POST" action="{{ route('super-admin.demo-requests.destroy', $demoRequest) }}" onsubmit="return confirm('Archive this demo request?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form></td></tr>@empty<tr><td colspan="6" class="text-muted">No demo requests found.</td></tr>@endforelse
</tbody></table>{{ $demoRequests->links() }}</div>
@endsection
