<div class="platform-card p-3"><div class="row g-3">
    <div class="col-md-4"><label class="form-label">School</label><select class="form-select" name="school_id"><option value="">Not set</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected(old('school_id', $payment->school_id)==$school->id)>{{ $school->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Owner</label><select class="form-select" name="school_owner_id"><option value="">Use school owner</option>@foreach($schools as $school)@if($school->owner)<option value="{{ $school->owner->id }}" @selected(old('school_owner_id', $payment->school_owner_id)==$school->owner->id)>{{ $school->owner->name }} - {{ $school->name }}</option>@endif @endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Plan</label><select class="form-select" name="subscription_plan_id"><option value="">No plan</option>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected(old('subscription_plan_id', $payment->subscription_plan_id)==$plan->id)>{{ $plan->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Amount</label><input class="form-control" type="number" step="0.01" min="0" name="amount" value="{{ old('amount', $payment->amount ?? 0) }}" required></div>
    <div class="col-md-2"><label class="form-label">Currency</label><input class="form-control" name="currency" value="{{ old('currency', $payment->currency ?? 'NGN') }}" maxlength="3" required></div>
    <div class="col-md-3"><label class="form-label">Method</label><select class="form-select" name="payment_method">@foreach(['manual','bank_transfer','cash','paystack'] as $method)<option value="{{ $method }}" @selected(old('payment_method', $payment->payment_method ?: 'manual')===$method)>{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['pending','paid','failed','rejected','refunded'] as $status)<option value="{{ $status }}" @selected(old('status', $payment->status ?: 'pending')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Payment reference</label><input class="form-control" name="payment_reference" value="{{ old('payment_reference', $payment->payment_reference) }}"></div>
    <div class="col-md-4"><label class="form-label">Receipt/invoice number</label><input class="form-control" name="receipt_number" value="{{ old('receipt_number', $payment->receipt_number) }}"></div>
    <div class="col-md-4"><label class="form-label">Payment date</label><input class="form-control" type="date" name="payment_date" value="{{ old('payment_date', optional($payment->payment_date)->format('Y-m-d')) }}"></div>
    <div class="col-md-6"><label class="form-label">Period start</label><input class="form-control" type="date" name="period_start" value="{{ old('period_start', optional($payment->period_start)->format('Y-m-d')) }}"></div>
    <div class="col-md-6"><label class="form-label">Period end</label><input class="form-control" type="date" name="period_end" value="{{ old('period_end', optional($payment->period_end)->format('Y-m-d')) }}"></div>
    <div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" rows="4" name="notes">{{ old('notes', $payment->notes) }}</textarea></div>
</div></div>
<div class="mt-3"><button class="btn btn-primary">{{ $button }}</button> <a class="btn btn-outline-secondary" href="{{ route('super-admin.payments.index') }}">Cancel</a></div>
